import type { Metadata } from 'next'
import {
  JetBrains_Mono,
  DM_Sans,
  Nunito_Sans,
  Montserrat
} from 'next/font/google'
import '../styles/globals.css'
import { Providers } from './providers'
import { ClerkProvider } from '@clerk/nextjs'

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-mono',
  subsets: ['latin']
})

const dmSans = DM_Sans({
  variable: '--font-sans',
  subsets: ['latin']
})

const nunitoSans = Nunito_Sans({
  variable: '--font-serif',
  subsets: ['latin']
})

const montserrat = Montserrat({
  variable: '--font-display',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'My Pro Blog',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="es" className="dark" suppressHydrationWarning>
        <body
          className={`${dmSans.variable} ${jetBrainsMono.variable} ${nunitoSans.variable} ${montserrat.className} antialiased`}
        >
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
